---
title: "Athlete Sleep Characteristics Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
    orientation: rows
    vertical_layout: fill
    css: ../css/styles.-default.css
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(tidyverse)
library(plotly)
library(tidyverse)
library(ggrepel)
library(data.table)
library(rvest)
library(DT)
library(DataExplorer)
library(recipes)
library(dplyr)
library(janitor)
library(umap)
library(forcats)
library(factoextra)
library(kableExtra)
library(crosstalk)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

asbq_psqi_df <- athslpbehaviour_df %>%
  clean_names() 

# Scale data

data_cleaned_scaled1 <- asbq_psqi_df %>%
  select(-c(asbq_global, psqi_total)) %>% 
  select(6:32)

data_cleaned_scaled <-   scale(data_cleaned_scaled1)

```




<!-- # Athlete Exploration -->

Clustering
============================================================

## Column {.sidebar data-width=400}
------------------------------------------------------------

<!-- #### How it works -->


This interactive plot provides a visual representation of the athlete clusters based on variables from their **Pittsburgh Sleep Quality Index (PSQI)** and **Athlete Sleep Behavior Questionnaire (ASBQ)** results. Selecting the dots (each representing an athlete) will populate an __Athlete Information__ downloadable table to get a detailed breakdown of the sleep-related characteristics of the selected athletes. 

<hr>


```{r}

shiny::numericInput(
  inputId = "kmeans_numbers",
  label = h4("Specify number of k-means Clusters"),
  value = 3
  
)

```

The optimal number of classification groups (clusters) can be determined using the *elbow method*. If the line chart looks like an arm, then the “elbow” (the point of inflection on the curve) is the best value of k.

<hr>

```{r}
# wss <- 0
# set.seed(1234)
# for (i in 1:10) {
#   km.out <- kmeans(data_cleaned_scaled, centers = i, nstart = 2)
#   wss[i] <-  km.out$tot.withinss
# }
# plot(1:10,
#      wss,
#      type = "b",
#      xlab = "No. of Clusters",
#      ylab = "Within groups SOS")

# Use map_dbl to run many models with varying value of k (centers)
tot_withinss <- map_dbl(1:10,  function(k){
  set.seed(1234)
  model <- kmeans(x = data_cleaned_scaled, centers = k)
  model$tot.withinss
})
 
# Generate a data frame containing both k and tot_withinss
elbow_df <- data.frame(
  k = 1:10,
  tot_withinss = tot_withinss
)
 
 
# Plot the elbow plot

ggplot1 <- ggplot(elbow_df, aes(x = k, y = tot_withinss)) +
  geom_line() + geom_point()+
  scale_x_continuous(breaks = 1:10)+
  labs(
    title = "Elbow plot to determine optimal no. of clusters",
    x = "Within groups SOS",
    y = "No. of clusters"
  )+
  theme_light()+
  theme(axis.text = element_text(size = 2))

renderPlot({
  ggplot1
  
}
)

```


```{r message=FALSE, warning=FALSE, include=FALSE}
k.high <- reactive({


## Edit number of clusters here
  set.seed(1234)
  data_cleaned_scaled %>% 
    kmeans(centers = input$kmeans_numbers) # reactive expression


})

```


```{r message=FALSE, warning=FALSE, include=FALSE}


k_means_complete <- reactive({


gender_grp <- asbq_psqi_df %>%
  select(gender)
name_grp <- asbq_psqi_df %>%
  select(name)
sport_grp <- asbq_psqi_df %>%
  select(sport)
psqi_cat <- asbq_psqi_df %>%
  select(psqi_cat)
asbq_grp <- asbq_psqi_df %>% 
  select(asbq_global)
psqi_grp <- asbq_psqi_df %>% 
  select(psqi_total)


  cbind(
    data_cleaned_scaled1,
    gender = gender_grp,
    name = name_grp,
    sport = sport_grp,
    psqi_total = psqi_grp,
    asbq = asbq_grp,
    psqi_cat = psqi_cat,
    cluster = k.high()$cluster
  )

})


shared_athletes <- reactive({
  
# Prepare umap  ----

umap_high <- data_cleaned_scaled %>%
  umap()

umap_high_results_tbl <- umap_high$layout %>%
  as_tibble() %>%
  set_names(c("x", "y")) %>%
  bind_cols(k_means_complete() %>% select(sport))

umap_kmeans_high_results_tbl <- umap_high_results_tbl %>%
  mutate(
    cluster = k_means_complete()$cluster,
    name = k_means_complete()$name,
    sport = k_means_complete()$sport,
    asbq = k_means_complete()$asbq,
    psqi = k_means_complete()$psqi_total,
    psqi_cat = k_means_complete()$psqi_cat
    
    
  ) %>%
  mutate(cluster = as_factor(cluster))

SharedData$new(umap_kmeans_high_results_tbl,
                                  key = ~ name,
                                  group = "name")


})

```


## Column 1 

### Athlete Segmentation Based on ASBQ & PSQI Characteristics

```{r}

output$plotly_1 <- renderPlotly({
  plot_ly(
    data = shared_athletes(),
    x = ~x,
    y = ~y,
    color = ~cluster,
    # colors="Dark2",
      text  = ~ str_c(
        "Name: ", name,
        "</br>",
        "Sport: ", sport,
        "</br>",
        "ASBQ Score: ", asbq,
        "</br>",
        "PSQI Score: ", psqi
        ),
      source = "A"
    ) %>%
    add_markers(size = 3) %>%
    highlight(
      on  = "plotly_selected",
      # off = "plotly_doubleclick",
      # selectize  = TRUE,
      # dynamic    = TRUE,
      persistent = TRUE


  ) %>%
    layout(legend=list(title=list(text='<b> Clusters </b>')))

})

plotlyOutput("plotly_1", height = "400px")


```


## Column 2

### Athlete Information

```{r}

output$table1 <- DT::renderDataTable({
  
  k_means_complete_simple <- k_means_complete() %>%
  select(
    name,
    sport,
    asbq_global,
    i_take_afternoon_naps_lasting_two_or_more_hours,
    i_use_stimulants_when_i_train_compete_e_g_caffeine,
    i_exercise_train_or_compete_late_at_night_after_7pm,
    i_consume_alcohol_within_4_hours_of_going_to_bed,
    i_go_to_bed_at_different_times_each_night_more_than_1_hour_variation,
    i_go_to_bed_feeling_thirsty,
    i_go_to_bed_with_sore_muscles,
    i_use_light_emitting_technology_in_the_hour_leading_up_to_bedtime_e_g_laptop_phone_television_video_games,
    i_think_plan_and_worry_about_my_sporting_performance_when_i_am_in_bed,
    i_think_plan_and_worry_about_issues_not_related_to_my_sport_when_i_am_in_bed,
    i_use_sleeping_pills_tablets_to_help_me_sleep,
    i_wake_to_go_to_the_bathroom_more_than_once_per_night,
    i_wake_myself_and_or_my_bed_partner_with_my_snoring,
    i_wake_myself_and_or_my_bed_partner_with_my_muscle_twitching,
    i_get_up_at_different_times_each_morning_more_than_1_hour_variation,
    at_home_i_sleep_in_a_less_than_ideal_environment_e_g_too_light_too_noisy_uncomfortable_bed_pillow_too_hot_cold,
    i_sleep_in_foreign_environments_e_g_hotel_rooms,
    travel_gets_in_the_way_of_building_a_consistent_sleep_wake_routine,
    psqi_total,
    comp1final,
    comp2final,
    comp3final,
    comp4final,
    comp5final,
    comp6final,
    comp7final,
    percentage,
    combined_mins,
    psqi_cat
    
  ) %>%
  mutate(
    Name = `name`,
    Sport = `sport`,
    `ASBQ Score` = asbq_global,
    `Afternoon naps` = i_take_afternoon_naps_lasting_two_or_more_hours,
    `Stimulant use` = i_use_stimulants_when_i_train_compete_e_g_caffeine,
    `Train late` = i_exercise_train_or_compete_late_at_night_after_7pm,
    `Consume alcohol` = i_consume_alcohol_within_4_hours_of_going_to_bed,
    `Varied bedtime` = i_go_to_bed_at_different_times_each_night_more_than_1_hour_variation,
    `Thirsty` = i_go_to_bed_feeling_thirsty,
    `Sore muscles` = i_go_to_bed_with_sore_muscles,
    `Light emitting device use` = i_use_light_emitting_technology_in_the_hour_leading_up_to_bedtime_e_g_laptop_phone_television_video_games,
    `Sport worries` = i_think_plan_and_worry_about_my_sporting_performance_when_i_am_in_bed,
    `Non-sport worries` = i_think_plan_and_worry_about_issues_not_related_to_my_sport_when_i_am_in_bed,
    `Sleeping pills` = i_use_sleeping_pills_tablets_to_help_me_sleep,
    `Bathroom use` = i_wake_to_go_to_the_bathroom_more_than_once_per_night,
    `Snoring` = i_wake_myself_and_or_my_bed_partner_with_my_snoring,
    `Muscle twitching` = i_wake_myself_and_or_my_bed_partner_with_my_muscle_twitching,
    `Varied waketime` = i_get_up_at_different_times_each_morning_more_than_1_hour_variation,
    `Environment issues` = at_home_i_sleep_in_a_less_than_ideal_environment_e_g_too_light_too_noisy_uncomfortable_bed_pillow_too_hot_cold,
    `Foreign environments` = i_sleep_in_foreign_environments_e_g_hotel_rooms,
    `Travel issues` = travel_gets_in_the_way_of_building_a_consistent_sleep_wake_routine,
    `PSQI Score` = psqi_total,
    `PSQI Category` = psqi_cat,
    `Comp. 1` = comp1final,
    `Comp. 2` = comp2final,
    `Comp. 3` = comp3final,
    `Comp. 4` = comp4final,
    `Comp. 5` = comp5final,
    `Comp. 6` = comp6final,
    `Comp. 7` = comp7final,
    `Sleep efficiency (%)` = percentage,
    `Sleep duration (mins)` = combined_mins
  ) %>%
  select(c(33:62))


shared_sleep_details <- SharedData$new(k_means_complete_simple,
                                       key = ~ Name,
                                       group = "name"
                                       )

datatable(
  data      = shared_sleep_details,
  extensions = 'Buttons',
  options = list(
                dom     = 'Bfrtip',
                # deferRender = TRUE,
                searching = TRUE,
                buttons = c('copy', 'csv', 'excel'),
                autoWidth = TRUE,
                scrollCollapse = TRUE,
                rownames = TRUE,
                scroller = TRUE,
                scrollX = TRUE,
                scrollY = "150px",
                fixedHeader = FALSE,
                class = 'cell-border stripe',
                fixedColumns = list(
                  leftColumns = 6,
                  heightMatch = 'none'
                  )
                
  )
)
  
}, server = FALSE)

DT::dataTableOutput("table1",
                    height = "40em")

```


Summary data
============================================================

## Column {.sidebar data-width=400}
------------------------------------------------------------

```{r}

dateRangeInput(
  inputId = "date_range",
  label   = h4("Date Range"),
  start   = min(asbq_psqi_df$date_administered),
  end     = max(asbq_psqi_df$date_administered),
  min     = min(asbq_psqi_df$date_administered),
  max     = max(asbq_psqi_df$date_administered),
  startview = "month")


shinyWidgets::pickerInput(
  inputId  = "picker_category_sport",
  label    = h4("Sport"),
  choices  = sort(as.character(unique(asbq_psqi_df$sport))),
  selected = sort(as.character(unique(asbq_psqi_df$sport))),
  multiple = TRUE,
  options  = list(
    `actions-box` = TRUE,
    size = 10,
    `selected-text-format` = "count > 3"
  )
)

# Add filter by gender

shinyWidgets::pickerInput(
  inputId  = "picker_category_gender",
  label    = h4("Gender"),
  choices  = sort(as.character(unique(asbq_psqi_df$gender))),
  selected = sort(as.character(unique(asbq_psqi_df$gender))),
  multiple = TRUE,
  options  = list(
    `actions-box` = TRUE,
    size = 10,
    `selected-text-format` = "count > 3"
  )
)


# Add filter by PSQI category

shinyWidgets::pickerInput(
  inputId  = "picker_category_psqi",
  label    = h4("PSQI category"),
  choices  = sort(as.character(unique(asbq_psqi_df$psqi_cat))),
  selected = sort(as.character(unique(asbq_psqi_df$psqi_cat))),
  multiple = TRUE,
  options  = list(
    `actions-box` = TRUE,
    size = 10,
    `selected-text-format` = "count > 3"
  )
)


# Add slider for psqi score

sliderInput(
  inputId = "slider_psqi_score",
  label = h4("PSQI score"),
  min = 0,
  max = max(asbq_psqi_df$psqi_total),
  value = c(0, max(asbq_psqi_df$psqi_total)),
  step = 1,
  round = TRUE
  
  )



# Add slider for ASBQ sscore

sliderInput(
  inputId = "slider_asbq_score",
  label = h4("ASBQ score"),
  min = 0,
  max = max(asbq_psqi_df$asbq_global),
  value = c(0, max(asbq_psqi_df$asbq_global)),
  step = 1,
  round = TRUE
  
  )

# Add slider for sleep duration

sliderInput(
  inputId = "slider_sleep_duration",
  label = h4("Sleep duration (hrs)"),
  min = 0,
  max = round(max((asbq_psqi_df$combined_mins/60)),1),
  value = c(0, round(max((asbq_psqi_df$combined_mins/60)),1)),
  step = 0.1,
  round = TRUE
  
  )


```



```{r}

asbq_psqi_tbl <- reactive({
  
  asbq_psqi_df %>%
    
    mutate(
      combined_hrs =  combined_mins/60
      
      
    ) %>% 
    
    
    dplyr::filter(date_administered %>% dplyr::between(left = ymd(input$date_range[1]),
                                         right = ymd(input$date_range[2]))) %>% 
    
    dplyr::filter(sport %in% input$picker_category_sport) %>% 
    
    dplyr::filter(gender %in% input$picker_category_gender) %>% 
    
    dplyr::filter(psqi_cat %in% input$picker_category_psqi) %>%

    dplyr::filter(combined_hrs %>% dplyr::between(left=input$slider_sleep_duration[1],
                                           right =input$slider_sleep_duration[2])) %>% 
    
    
    dplyr::filter(psqi_total %>% dplyr::between(left=input$slider_psqi_score[1],
                                           right =input$slider_psqi_score[2])) %>% 
    
    dplyr::filter(asbq_global %>% dplyr::between(left=input$slider_asbq_score[1],
                                           right =input$slider_asbq_score[2]))
  
  
})

```

## Column 1

## Athlete Information

```{r}
output$table2 <- DT::renderDataTable({
  
  asbq_psqi_summary <- asbq_psqi_tbl() %>%
    select(
      name,
      gender,
      sport,
      percentage,
      combined_mins,
      psqi_total,
      asbq_global
    ) %>%
    mutate(
      Name = `name`,
      Sport = `sport`,
      Gender = `gender`,
      `ASBQ Score` = asbq_global,
      `Sleep efficiency (%)` = round(percentage,1),
      # `Sleep duration (mins)` = combined_mins,
      `Sleep duration (hrs)` = round(combined_mins/60,1),
      `PSQI Score` = `psqi_total`
      ) %>% 
    select(8:14)
   
   shared_asbq_psqi_details <- SharedData$new(asbq_psqi_summary)

datatable(
  data      = shared_asbq_psqi_details,
  extensions = 'Buttons',
  options = list(
                dom     = 'Bfrtip',
                # deferRender = TRUE,
                searching = TRUE,
                buttons = c('copy', 'csv', 'excel'),
                autoWidth = TRUE,
                scrollCollapse = TRUE,
                rownames = TRUE,
                scroller = TRUE,
                scrollX = TRUE,
                scrollY = "768px",
                fixedHeader = FALSE,
                class = 'cell-border stripe'
                
  )
)
  
}, server = FALSE)

DT::dataTableOutput("table2")
    

```

## Group Summary Information

```{r}

output$table3 <- DT::renderDataTable({
  
  asbq_psqi_summary2 <- asbq_psqi_tbl() %>%
    select(
      percentage,
      combined_mins,
      psqi_total,
      asbq_global
    ) %>%
    mutate(
      `ASBQ Score` = asbq_global,
      `Sleep efficiency (%)` = percentage,
      # `Sleep duration (mins)` = combined_mins,
      `Sleep duration (hrs)` = round(combined_mins/60,1),
      `PSQI Score` = `psqi_total`
      
    ) %>% 
    select(5:8) %>% 
    summarise(
      `Average ASBQ Score` = round(mean(`ASBQ Score`),1),
      `Average PSQI Score` = round(mean(`PSQI Score`),1),
      # `Average sleep duration (mins)` = round(mean(`Sleep duration (mins)`),1),
      `Average sleep duration (hrs)` = round(mean(`Sleep duration (hrs)`),1),
      `Average sleep efficiency (%)` = round(mean(`Sleep efficiency (%)`),1)
    )
    
     shared_asbq_psqi_details2 <- SharedData$new(asbq_psqi_summary2)

datatable(
  data      = shared_asbq_psqi_details2,
  extensions = 'Buttons',
  options = list(
                dom     = 'Bfrtip',
                # deferRender = TRUE,
                searching = TRUE,
                buttons = c('copy', 'csv', 'excel'),
                autoWidth = TRUE,
                scrollCollapse = TRUE,
                rownames = TRUE,
                scroller = TRUE,
                scrollX = TRUE,
                scrollY = "500px",
                fixedHeader = FALSE,
                class = 'cell-border stripe'
                
  )
)
  
}, server = FALSE)


DT::dataTableOutput("table3")

```






